################################### English language #####################################
[en]
languageName = "EN"
languageCode = "en-US"
contentDir = "content/english"
weight = 1
########### footer content ##########
footer_title = "Contact information"
footer_url = "https://www.w3.org/WAI/WCAG2AA-Conformance"
footer_alt = "Level AA conformance, W3C WAI Web Content Accessibility Guidelines 2.2"
footer_image = "https://www.w3.org/WAI/WCAG22/wcag2.2AA-blue"
footer_image_fallback = "Level AA conformance, W3C WAI Web Content Accessibility Guidelines 2.2"
footer_content = """
AccessLiaison by ALAS doo<br />
Rudjera Boskovica 20, Novi Sad, Serbia<br />
[info@accessliaison.com](mailto:info@accessliaison.com)
"""
