################################### English language #####################################
[en]
languageName = "EN"
languageCode = "en-US"
contentDir = "content/english"
weight = 1
########### footer content ##########
footer_menu_left = "Company"
footer_menu_middle = "Products"
footer_menu_right = "Support"
footer_content = """
AccessLiasion by Alas doo
Dimitrija Tucovica 20, Zrenjanin, Serbia
[info@alasdoo.com](mailto:info@alasdoo.com)
"""
